Add links to jupyter tutorials in getting started guide.
ludwig-ai/ludwig-docs pull request #275
Opened 2023-02-27 06:23 UTC by justinxzhao

The existing getting started guide is still pretty good.

For technical readers who want to jump into code right away, it seems useful to add links to Jupyter notebooks on the Getting Started guide.

2023-02-27 06:59 UTC, tgaddair approved these changes

2023-02-27 07:01 UTC, tgaddair requested changes
Looking through these notebooks, I actually wouldn't put this front and center to a first-time users.

2023-03-01 16:49 UTC, justinxzhao commented
> Looking through these notebooks, I actually wouldn't put this front and center to a first-time user.
> 
> * They use Ludwig master, not the release version.
> * They use the (kinda clunky) Python API, not the CLI, which most early users tend to prefer.
> * They're a bit overwheming in output. I don't think we should ask the users to grok all the metrics, etc. right from the start.
> 
> I would, however, link to the Examples section of the docs, where these examples should live, and give them a call to action to go check it out.

Ah! It seems I incorrectly assumed that most early users would prefer a real Python example in a hosted Jupyter notebook over the CLI. That said, we have CLI versions of both of these notebooks, so linking to the `examples/` or `tutorials/` subdir more broadly SGTM.

2023-03-02 16:57 UTC, tgaddair commented
@justinxzhao I think having a notebook version is good for folks who want to "follow along"l My suggestion would be to create a notebook form of the tutorial presented in the Getting Started docs. We could start with a CLI notebook, then also provide a Python API notebook as well.

2023-09-12 01:01 UTC, closed without merging